// Generated by CIRCT firtool-1.137.0-1-gfcc42190a

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Borg(	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
  input         clock,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
                reset,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
  input  [5:0]  io_address,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  input  [31:0] io_data_in,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  input  [1:0]  io_data_write_n,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
                io_data_read_n,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  output [31:0] io_data_out,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  output        io_data_ready,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  input  [7:0]  io_ui_in,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  output [7:0]  io_uo_out,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  output        io_user_interrupt	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
);

  reg  [31:0] operand_A;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28
  reg  [31:0] operand_B;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:22:28
  reg  [31:0] sum_result;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:41:29
  wire        is_writing = io_data_write_n == 2'h2;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :30:38
  always @(posedge clock) begin	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    if (reset) begin	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      operand_A <= 32'h0;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28
      operand_B <= 32'h0;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:22:28
    end
    else begin	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      if (is_writing & ~(|io_address))	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28, :30:38, :31:22, :32:{25,37}, :33:23
        operand_A <= io_data_in;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28
      if (is_writing & (|io_address) & io_address == 6'h4)	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:22:28, :30:38, :31:22, :32:{25,37}, :34:{32,44}
        operand_B <= io_data_in;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:22:28
    end
    sum_result <= operand_A + operand_B;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28, :22:28, :41:{29,40}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    initial begin	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
        `INIT_RANDOM_PROLOG_	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
        end	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
        operand_A = _RANDOM[2'h0];	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :21:28
        operand_B = _RANDOM[2'h1];	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :22:28
        sum_result = _RANDOM[2'h2];	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :41:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      `FIRRTL_AFTER_INITIAL	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_data_out =
    io_address == 6'h8
      ? sum_result
      : io_address == 6'h4 ? operand_B : (|io_address) ? 32'h0 : operand_A;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :21:28, :22:28, :32:25, :34:32, :41:29, :44:46
  assign io_data_ready = 1'h1;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :52:19
  assign io_uo_out = 8'h0;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :53:15
  assign io_user_interrupt = 1'h0;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :44:46
endmodule

